FROM ubuntu:latest

LABEL maintainer="akrishnan@quansight.com"
# Updates
RUN apt-get update 
RUN apt-get -qq update && apt-get -qq -y install make cmake curl bzip2 \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3 \
    && conda update conda \
    && apt-get -qq -y remove curl bzip2 \
    && apt-get -qq -y autoremove \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
    && conda clean --all --yes

# PyTorch Specific Installation
RUN conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing
RUN apt-get update && apt-get install -y build-essential
# Creating new workdirs
RUN mkdir torch/
